// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl-PtmiBaRZtEPAxynGaFc3IGKbx8pP9Y',
    appId: '1:78461604531:web:54ae65383a08b7dbeb16c6',
    messagingSenderId: '78461604531',
    projectId: 'authpractice121621',
    authDomain: 'authpractice121621.firebaseapp.com',
    storageBucket: 'authpractice121621.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW-WiwAr2vvA6PO0krWslpUXjhBeCEGjQ',
    appId: '1:78461604531:android:bfeb7a8b2a877d21eb16c6',
    messagingSenderId: '78461604531',
    projectId: 'authpractice121621',
    storageBucket: 'authpractice121621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMCLFSvbPzyyzd8LmGnX56Zcptc0Dqw34',
    appId: '1:78461604531:ios:a518d315f54ab7dbeb16c6',
    messagingSenderId: '78461604531',
    projectId: 'authpractice121621',
    storageBucket: 'authpractice121621.firebasestorage.app',
    iosBundleId: 'com.mindmend.app',
  );

}